import { useNavigate } from "react-router-dom";
import { MyButton } from "./signUpBtn";
import forInvestorImage from "../assets/investor-legal-structure.webp";
import forOwnersImage from "../assets/asset-owner-legal-structure.webp";

export const TokunizeAdvantages: React.FC<{ componentFor: "investors" | "owners" }> = ({ componentFor }) => {
    const navigate = useNavigate();

    const getStartedLink = () => {
        navigate("/request-invitation/");
    };

    // Mapa de imágenes
    const images = {
        investors: forInvestorImage,
        owners: forOwnersImage,
    };

    const selectedImage = images[componentFor] || forInvestorImage; 


    return (
        <article className="min-h-screen flex flex-col my-12 text-gray-800">
            <h4 className=" text-3xl sm:text-4xl sm:text-center  font-semibold text-black mb-3 mx-5  md:px-0">Our Unfair Advantage</h4>
            <p className="text-gray-500 md:text-center pb-5 md:w-[60%] lg:w-[45%]  mx-auto mb-5 px-5 md:px-0">Combining full legal compliance with instant liquidity whilst investing in premium commercial real estate.</p>

            {/* Section 1 */}
            <section className="flex flex-col lg:flex-row items-center px-[20px] md:px-[60px] space-x-5  bg-black ">
                <aside className="w-full lg:w-1/2  py-[120px] space-y-4 px-5 sm:space-y-6">
                    <h3 className="text-2xl sm:text-3xl font-semibold  text-animated-gradient">Regulatory Compliant & Legally Secure</h3>
                    <p className="text-white leading-relaxed">
                        Each property’s title deed on our platform is held by a DAO LLC, ensuring compliance with UK regulations for fractional real estate. As a shareholder, owning tokens in the DAO LLC gives you legal ownership of the property.
                    </p>
                    <ul className="list-disc list-inside space-y-2 text-white">
                        <li><span className="font-semibold">Buy Tokens:</span> Secure your share in the DAO LLC.</li>
                        <li><span className="font-semibold">Earn & Grow:</span> Collect rental income & benefit from asset appreciation.</li>
                        <li><span className="font-semibold">Participate:</span> Vote on decisions affecting the property.</li>
                        <li><span className="font-semibold">Professional Management:</span> Skilled managers handle daily operations.</li>
                        <li><span className="font-semibold">Sell Anytime:</span> Easily trade your tokens on our marketplace.</li>

                    </ul>
                    <p className="text-animated-gradient text-lg font-bold leading-relaxed">
                        Invest, earn, participate—enjoy flexible, seamless real estate ownership.
                    </p>
                </aside>
                <div className="w-full pb-[120px] lg:pb-0 mt-5 lg:mt-0 lg:w-1/2 mb-6 lg:mb-0 flex float-right justify-center lg:justify-end">
                    <img
                        loading="lazy"
                        alt={`${componentFor === "investors" ? "Investors" : "Owners"} Legal compliance illustration`}
                        src={selectedImage}
                    />
                </div>
            </section>

            {/* Section 2 */}
            <section className="flex bg-white px-[20px] md:px-[60px] flex-col lg:flex-row min-h-[700px] lg:h-[700px] items-center gap-6 lg:gap-8 py-8 sm:py-10 lg:py-16">
                {/* Cards Section */}
                <div className="w-full lg:w-1/2 space-y-4   sm:space-y-6 order-2 lg:order-1">
                    <div className="bg-black   p-6 rounded-lg shadow-xl">
                        <h4 className="text-xl sm:text-xl text-animated-gradient font-semibold text-white">Tokunize Pool</h4>
                        <p className="text-white mt-2">
                            A liquidity pool that gathers funds from anonymous contributors, facilitating decentralized real estate trading on the Tokunize Marketplace with an automated market maker (AMM).
                        </p>
                    </div>

                    <div className="bg-black p-4 sm:p-6 rounded-lg shadow-xl">
                        <h4 className="text-xl sm:text-xl font-semibold text-white text-animated-gradient">Earn Passive Income</h4>
                        <p className="text-white mt-2">
                            By committing funds to the liquidity pool, you earn a share of the fees generated by the AMM on the Tokunize Marketplace, with an estimated APY of 5%+ depending on the property pool.
                        </p>
                    </div>

                    <div className="bg-black p-4 sm:p-6 rounded-lg shadow-xl">
                        <h4 className="text-xl sm:text-xl font-semibold text-white text-animated-gradient">Flexible Access & Profit Potential</h4>
                        <p className="text-white mt-2">
                            Withdraw your committed funds and earned yield from the liquidity pool at any time, with profits that naturally fluctuate based on market performance.
                        </p>
                    </div>
                </div>

                {/* Image/Graphic */}
                <div className="w-full lg:w-1/2 rounded-lg flex flex-col space-y-5 bg-black p-10  lg:p-6 h-full justify-center items-center order-1 lg:order-2">
                    <h3 className="text-3xl sm:text-[43px] text-animated-gradient   font-bold text-[#375B0A] text-center mb-4">Liquid Real Estate is Here</h3>
                    <p className="text-2xl  text-white text-center font-semibold">
                        Buy and sell commercial real estate as effortlessly as trading shares on the stock market.
                    </p>
                    <p className="text-2xl  text-white text-center font-semibold">
                        Diversify across 100+ premium properties in the UK starting at just £1,000 and sell with instant liquidity anytime.
                    </p>
                </div>
            </section>

            {/* CTA Section */}
            <div className="bg-gray-100 py-8 px-6 sm:px-10 flex flex-col items-center text-center">
                <p className="text-xl sm:text-2xl md:text-3xl  lg:text-5xl sm:w-[60%]  font-bold text-gray-800 mb-4">Put your money to work in fractional real estate ownership.</p>
                <MyButton
                    label="Get Started"
                    parentMethod={getStartedLink}
                />
            </div>
        </article>
    );
};



// {
//     "categoryId": 15,
//     "categoryName": "Key Terminology",
//     "questions": [
//       {
//         "id": "1",
//         "title": "What is an inspection contingency?",
//         "content": "Also known as a 'due diligence contingency,' the inspection contingency is a clause sometimes offered in a purchase agreement that grants buyers a predetermined amount of time during escrow to perform any necessary inspections."
//       },
//       {
//         "id": "2",
//         "title": "What is an inspection?",
//         "content": "An inspection happens when buyers pay a licensed professional inspector to visit the home and prepare a report on its condition and any needed repairs. The inspection often happens as part of the due diligence period, so buyers can fully assess if they want to buy a particular home as is, or ask the seller to either complete or pay for certain repairs."
//       },
//       {
//         "id": "3",
//         "title": "What is an earnest money deposit?",
//         "content": "An earnest money deposit (EMD), sometimes referred to as a 'good faith deposit', is the initial funds that a buyer is asked to put down once a seller accepts the buyer’s offer. It shows not only that the buyer is serious about buying, but that they are also willing to put their money where their mouth is. The amount of the EMD can vary between 1 to 5 percent of the sales price. The EMD is often held by an escrow company."
//       },
//       {
//         "id": "4",
//         "title": "What is a purchase and sale agreement (PSA)?",
//         "content": "A purchase and sale agreement is commonly referred to as a written contract between the buyer and seller, which outlines the terms of the parties to sell and purchase real property. When a home is 'under contract', it usually signifies that the buyer and seller have formalized their commitment to sell and purchase the real property."
//       },
//       {
//         "id": "5",
//         "title": "What does IRR mean?",
//         "content": "IRR stands for Internal Rate of Return, which is an annualized return for equity investments that includes cash distributions and appreciation."
//       },
//       {
//         "id": "6",
//         "title": "What is cash on cash return (CoC)?",
//         "content": "The cash return on an investment compared to the amount of cash invested. For example, an investment with cash distributions of £50 on a £1,000 investment has a 5% cash on cash return."
//       },
//       {
//         "id": "7",
//         "title": "What is appreciation?",
//         "content": "A measure of the estimated increase in value of an asset over a time period."
//       },
//       {
//         "id": "8",
//         "title": "What is cap rate?",
//         "content": "The cap rate is the Net Operating Income (NOI) divided by the purchase price. The cap rate is an indicator of the risk and return of a property. It tells you the return of an investment before financing costs."
//       },
//       {
//         "id": "9",
//         "title": "What is Net Operating Income (NOI)?",
//         "content": "Net Operating Income (NOI) is the gross profit of a rental property. It’s calculated as gross rents minus all expenses other than interest."
//       },
//       {
//         "id": "10",
//         "title": "What does CapEx mean?",
//         "content": "CapEx, or Capital Expenditures, are defined as new purchases or major improvements/renovations that extend the life of a property, such as replacing a roof, adding an extension, or finishing the basement. This term also covers equipment and supplies required to make these improvements. Generally, these are one-time, major expenses."
//       },
//       {
//         "id": "11",
//         "title": "What is a single-family home?",
//         "content": "A type of rental property that is designed for just one family to live in. This can be a typical house or townhouse. Duplexes and apartment buildings are considered to be 'multi-family' housing because the property can house multiple families."
//       },
//       {
//         "id": "12",
//         "title": "What is a duplex?",
//         "content": "A duplex is a multi-family home that has two units in the same building. These two units always share a common wall, but the floor plan can vary. Units can be arranged either side by side or stacked on top of one another, each occupying an entire floor or two of the building. Each unit has a separate entrance and there is no interior connection between the two units."
//       },
//       {
//         "id": "13",
//         "title": "What is a triplex?",
//         "content": "A triplex is a multi-family home that has three units in the same building. These three units always share a common wall, but the floor plan can vary. Units can be arranged either side by side or stacked on top of one another, each occupying an entire floor or two of the building. Each unit has a separate entrance and there is no interior connection between the three units."
//       },
//       {
//         "id": "14",
//         "title": "What is diversification?",
//         "content": "The process of investing in different investments to reduce a portfolio's overall risk."
//       },
//       {
//         "id": "15",
//         "title": "What is land?",
//         "content": "Includes undeveloped property, vacant land, and agricultural land (farms, orchards, ranches, and timberland)."
//       },
//       {
//         "id": "16",
//         "title": "What are operating expenses?",
//         "content": "Operating Expenses include all of the anticipated costs for operating the rental property. Some expenses include Insurance, Property Tax, Vacancy, Maintenance, and Property Management."
//       },
//       {
//         "id": "17",
//         "title": "What is residential real estate?",
//         "content": "Any property used for residential purposes. Examples include single-family homes, condos, cooperatives, duplexes, townhouses, and multifamily residences with fewer than five individual units/flats."
//       },
//       {
//         "id": "18",
//         "title": "What is commercial real estate?",
//         "content": "Any property used exclusively for business purposes, such as apartment complexes, gas stations, grocery stores, hospitals, hotels, offices, parking facilities, restaurants, shopping centers, stores, and theaters."
//       },
//       {
//         "id": "19",
//         "title": "What is industrial real estate?",
//         "content": "Any property used for manufacturing, production, distribution, storage, and research and development. Examples include factories, power plants, and warehouses."
//       },
//       {
//         "id": "20",
//         "title": "What is special purpose property?",
//         "content": "Property used by the public, such as cemeteries, government buildings, libraries, parks, places of worship, and schools."
//       },
//       {
//         "id": "21",
//         "title": "What is capital gains tax?",
//         "content": "Capital gain or loss is the difference in the value of a property compared to its purchase price. If there is a gain, it is realised after the asset is sold. A short-term capital gain is one year or less; a long-term gain is more than a year. Both must be claimed on your income taxes, but short-term capital gains have a higher tax rate than long-term capital gains."
//       },
//       {
//         "id": "22",
//         "title": "What are closing costs?",
//         "content": "Closing costs are the fees paid at the end of a real estate transaction. These fees vary depending on where you live, the property you buy, and the type of loan you choose. There are costs associated with inspections, transfer of title, loan origination fees, etc."
//       },
//       {
//         "id": "23",
//         "title": "What is HVAC?",
//         "content": "Heating, Ventilating, and Air Conditioning (HVAC) systems are used to heat and cool a house. Sometimes HVAC units have integrated heating and cooling systems, while other times the HVAC system of a rental property may consist of an air conditioning unit and a separate furnace unit."
//       }
//     ]
//   }