# Generated by Django 4.2.16 on 2024-09-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('subtitle', models.TextField()),
                ('first_section', models.TextField()),
                ('day_posted', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('second_section', models.TextField(blank=True, null=True)),
                ('third_section', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-day_posted'],
                'indexes': [models.Index(fields=['-day_posted'], name='blog_articl_day_pos_665505_idx')],
            },
        ),
    ]
