# Generated by Django 4.2.16 on 2024-09-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.IntegerField(default=0)),
            ],
        ),
    ]
