# Generated by Django 4.2.16 on 2024-09-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('visits', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogStatistics',
        ),
    ]
