# Generated by Django 4.2.16 on 2024-09-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='five_section',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='fourth_section',
            field=models.TextField(blank=True, null=True),
        ),
    ]
