# Generated by Django 4.2.7 on 2024-08-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_contactedclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactedclient',
            name='property_county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactedclient',
            name='property_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactedclient',
            name='property_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactedclient',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
