# Generated by Django 4.2.16 on 2024-10-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_contactedclient_property_county_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestInvitationClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('contacted_at', models.DateTimeField(auto_now_add=True)),
                ('how_hear_about_us', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['contacted_at'],
            },
        ),
    ]
