# Generated by Django 4.2.16 on 2024-10-23 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_requestinvitationclients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestinvitationclients',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='requestinvitationclients',
            name='how_hear_about_us',
        ),
        migrations.RemoveField(
            model_name='requestinvitationclients',
            name='last_name',
        ),
    ]
