# Generated by Django 4.2.16 on 2024-10-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_remove_requestinvitationclients_email_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinvitationclients',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='requestinvitationclients',
            name='how_heard_about_us',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='How Heard About Us'),
        ),
        migrations.AddField(
            model_name='requestinvitationclients',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='requestinvitationclients',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name'),
        ),
    ]
