# Generated by Django 4.2.16 on 2024-10-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_requestinvitationclients_email_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email_address', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('how_heard_about_us', models.CharField(max_length=200, verbose_name='How Heard About Us')),
                ('contacted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['contacted_at'],
            },
        ),
        migrations.DeleteModel(
            name='RequestInvitationClients',
        ),
    ]
