# Generated by Django 4.2.16 on 2024-10-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_requestedinvitation_delete_requestinvitationclients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedinvitation',
            name='email_address',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
    ]
